bryceeppler/snapcaster-client

- pages/updates.tsx
- stores/store.ts
Domain No Longer Exists: https://www.lukescards.com/
I'm assuming the store doesn't exist or they just forgot to renew their Go Daddy domain name.
> Removing Lukes Cards

- components/Navbar.tsx
- pages/advancedsearch.tsx
- stores/advancedStore.ts
**Added Discord non expiring link to navbar**
**Advanced Search Fixes**
- input tag removes leading and trailing white spaces
- user can hit enter on their keyboard in the text box to search instead of hitting the search button
- added the confetti foil type that I forgot to put in originally
> Added Discord to Nav Bar and Advanced Search Fixes

- components/NavbarNew.tsx
- pages/about.tsx
- pages/card-guide/index.tsx
- stores/store.ts
Fixing a broken image on the card guide index page (please double check that the images load fine).
Added the about page as an option in the mobile nav bar.
> Added About page to mobile nav and fixed broken image

- pages/wishlist/index.tsx
- stores/store.ts
Bug fix for user "TheStrider"
- removed leading and trailing spaces in single search.
- fixed a ui bug when editing wishlists from the /wishlist page. If you are in edit mode and click anywhere like the text box to edit the name it would redirect to the href. I also made some adjustments like remove the pointer cursor when they're in edit mode.
> removed leading and trailing spaces in single search and UI bug fixes

- components/advanced-search/advanced-catalog-row.tsx
- components/advanced-search/advanced-filter-dropdown.tsx
- components/single-search/single-grid-item.tsx
- components/single-search/single-list-item.tsx
- components/single-search/single-table.tsx
- stores/advancedStore.ts
- Single Search was using the price after discount. I swapped them with the price before discount until we want to implement the promo code badges.
**Single Search Result**
**Advanced Search Result**
- Reset Filter now properly deselects all enabled filtered options in advanced search. (Specifically the Promo Pack and Japanese Alternate Art Toggles)
- UX Adjustment to the advanced-filter-dropdown component. Clicking the dropdown would auto focus the search input and auto toggle mobile virtual keyboards which take up half the screen. Added 1 line of code that makes it so it doesn't auto focus by default.
> Single Search Adjustment, Reset Filter Bug Fix,  Advanced Filter Dropdown UX Adjustment

- components/autofill-searchbox.tsx
- components/single-search/multitcg-searchbox.tsx
- pages/advancedsearch.tsx
- pages/index.tsx
- pages/multisearch/index.tsx
- stores/multiSearchStore.ts
- utils/analytics.ts
Added existing search event/search click trigger from tag manager to capture single search and advanced search queries.
I just pass in searchType = {single | advanced} as a prop in the MultiTcgSearchbox since advanced search and single search both use the same component which gets passed down into the handleQuerySingleCard function in utils\analytics.ts.
**Files Affected:**
- pages/index.tsx
- pages/multisearch/index.tsx
- pages/advancedsearch.tsx
- components/single-search/multitcg-searchbox.tsx
- components/autofill-searchbox.tsx
- utils/analytics.ts
- stores/multiSearchStore.ts
**Examples Search Event Triggering In Preview Mode**
> Single Search, Multi Search, Advanced Search Trigger

- pages/advancedsearch.tsx
- stores/store.ts
Purpose: Add Crystal Commerce to the websites options in advanced search.
**Files Updated**
- stores/store.ts
Note: After I get f2f and conduct commerce done, everythings going to switch to the catalog endpoint and then I'll be able to plug and play the row, card, and grid search results. After I do that I'll probably look to remove the advanced search page and integrate it all on the home page
**Screenshot of a conduct commerce website populating in the sets dropdown**
> SNAP-127 Adding Crystal Commerce Stores to Advanced Page

- CHANGELOG.md
- components/advanced-search/advanced-catalog-row.tsx
- components/multi-search/multi-website-combobox.tsx
- components/single-search/single-grid-item.tsx
- components/single-search/single-list-item.tsx
- components/single-search/single-table.tsx
- pages/advancedsearch.tsx
- pages/multisearch/index.tsx
- stores/globalStore.ts
- stores/multiSearchStore.ts
- stores/store.ts
- types/website.ts
- Changed all references to website.code to website.slug to match new database schema
- Updated website types to reflect new endpoint return data
```json
{
"websiteList": [
{
"slug": "houseofcards",
"name": "House of Cards",
"backend": [
"BINDER_POS"
],
"url": "https://houseofcards.ca/",
"tcgs": [
"MTG",
"POKEMON",
"YUGIOH",
"LORCANA"
]
},
{
"slug": "exorgames",
"name": "Exor Games",
"backend": [
"BINDER_POS"
],
"url": "https://exorgames.com/",
"tcgs": [
"MTG",
"POKEMON",
"YUGIOH",
"LORCANA"
]
},
{
"slug": "abyss",
"name": "Abyss Game Store",
"backend": [
"BINDER_POS"
],
"url": "https://www.abyssgamestore.com/",
"tcgs": [
"MTG",
"POKEMON",
"YUGIOH",
"LORCANA"
]
}
]
}
```
> change website code to website slug

- CHANGELOG.md
- pages/multisearch/index.tsx
**purpose:** hard code the new partnered stores in the recommended stores box in multi search
**Files Changed:**
- _pages/multisearch/index.tsx_
- Hard coded exor games, level up games, and chimera games as options in the recommended stores options in /pages/multisearch/index.tsx
- you can add and remove websites in the reccomendedWebsites list which contains a list of reccomended stores by slug
- this pull from the postgres tables in the future
> Recommened stores fix

- components/buylists/buylist-cart.tsx
- components/buylists/buylist-filter-container.tsx
- components/buylists/buylist-search-box.tsx
- components/buylists/filter-drop-down-multiple.tsx
- components/buylists/result-card.tsx
- pages/buylists/index.tsx
**Purpose:** Adjust the buylists result card so the card image displays on the right side to make it easier for users to scroll down with their right hand and prevent clicking a drop down they didn't mean to click. Also adjusted the mobile filter sheet to automatically close when the user clicks apply filter rather than making them click the close button an additional time.
> Buylist Mobile UI QOL Updates.

- components/ui/select.tsx
**Purpose:** ShadCN's provided code for the Select Component comes with a bug where clicking the selectable dropdown options on touch screen devices such as mobile also causes interactive elements such as buttons hidden behind it to also be clicked. This was causing the add to cart button to also be clicked when a user selected a store option that overlapped it to trigger both at the same time.
**Affected Files:**
- _components/ui/select.tsx_
**Changes:** Updated the ref for the select primitive to stop it's default behavior on screen touch. This will fix this behavior any other place we use Shadcn's<Select> component as well.
> fixed Shadcn Select component bug affecting touch screen devices

- components/buylists/buylist-filter-container.tsx
- components/buylists/filter-drop-down-multiple.tsx
- components/ui/dropdown-menu.tsx
- components/ui/select.tsx
- stores/buyListStore.ts
**Purpose:** Fixed Shadcn's premade components for DropDownMenu and Select from auto opening when scrolling over on mobile. Fixed the filters on buylists from not being persistent when switching from mobile to desktop view.
**Relevant files Affected:**
- components/buylists/buylist-filter-container.tsx
- components/buylists/filter-drop-down-multiple.tsx
- components/ui/dropdown-menu.tsx
- components/ui/select.tsx
> fixed dropdowns from opening when mobile scrolling and persistant filters

- components/search-bar/search-bar.tsx
Purpose: Fixing a bug preventing the single search tcg selector from opening up when the user selects it.
> Adjusting usage of <Select> in the single search bar

- components/single-search/single-catalog-container.tsx
- components/single-search/single-filter-container.tsx
- pages/index.tsx
- stores/useSingleSearchStore.ts
**Purpose:** Seperated the single search loading logic for the filter section and the card result section. Applying a filter would set loading to false in index.tsx which would rerender the filter section. As a result, a user could scroll through a large set list to apply a filter which would rerender the entire filter box and bring the scrollable section back to the top even though the user likely wants to continue scrolling down to apply more filters.
**Relevant Files Affected:**
- stores/useSingleSearchStore.ts
-  pages/index.tsx
- components/single-search/single-catalog-container.tsx
- components/single-search/single-filter-container.tsx
**Separated loading into loadingCardResults and  loadingFilterResults**
**Description:** removed use of the skeleton and loading logic in index.tsx …
> Adjusted Single Search Loading Logic

- pages/index.tsx
I accidently set the width for the giveaway banner to w-min and whitespace-nowrap causing mobile styling issues. I removed those options in the banner class names and it now displays properly on desktop and mobile
> fixed a giveawway banner width styling issue

- stores/multiSearchStore.ts
Purpose: Adding the ca prefix to the multisearch alias in the zustand multisearch store.
> adding ca prefix to multisearch alias

- components/single-search/single-filter-container.tsx
- components/subscription-options.tsx
**Purpose:** Allow free users to get full access to advanced filtering options for single search. (No need to change anything server side)
**Relevant Files Affected:**
- _components/single-search/single-filter-container.tsx_
- _components/subscription-options.tsx_
**Allow Free Users To Use Advanced Search:**
**Description:** Removed isAuthenticard checks, allowing all users to access the advanced filtering options.
**Files Affected:**
- _components/single-search/single-filter-container.tsx_
> SNAP-83 removed advanced filter restriction

- components/search-bar/nav-search-bar copy.tsx
- components/search-bar/search-bar.tsx
**Purpose:** Fix wrong text colour styling for the search bar and autocomplete which made it impossible to read on light mode. Fixed autocomplete bug that caused it to become visible again if a user selected an autocomplete option when it shouldn't appear again.
Affected Files:
components/search-bar/nav-search-bar copy.tsx
components/search-bar/search-bar.tsx
> fixed styling and bug for autocomplete

- components/ui/navbar.tsx
Removed This block of code on line 226 that was causing a visual bug:
{searchResults && currentPath == '/' && (
<div className="h-[0.5px] mx-5 bg-border w-[calc(100%-40px)]"></div>
)}
The other code adjustments to the file changed were just tailwind prettier auto formatting.
> removed mobile navbar component bug

- components/sealed/sealed-catalog-item.tsx
- components/single-search/single-catalog-item.tsx
- components/vendors/single-catalog-item.tsx
**Purpose:** Fixed long coupon codes from overflowing outside of the card container it's in.
**Relevant Files Changed:**
- components/sealed/sealed-catalog-item.tsx
- components/single-search/single-catalog-item.tsx
- components/vendors/single-catalog-item.tsx
**(1) Fixed long coupon codes:**
All that was added was a "break-all" to the class name of the span that holds the coupon code to allow the characters go to a new line. It was was just 3 lines of code across 3 files and all the other adjustments are just prettier auto formatting.
> fixed long coupon codes overflowing in container

- components/main-page-layout.tsx
- components/ui/footer.tsx
- components/ui/navbar.tsx
**Purpose:**
Adjusted the main page layout to prevent overlapping the side banner with the footer. Updated our socials (FB & Instagram) into our footer. Reordered items listed in the mobile nav and footer.
**Relevant Filed Changed:**
- components/main-page-layout.tsx
- components/ui/footer.tsx
- components/ui/navbar.tsx
**Adjusted the main page layout to prevent overlapping the side banner with the footer:**
Description: Restructured the layout into a flex container where the left container is the left banner, the middle container is the top banner and page contents (the children), and the right container contains the right banner. The resizing and padding behavior remain the same but now the side banners don't clip into the footer anymore.
> adjust layout to prevent side banner overlap & updated socials in footer

- components/buylists/buylist-catalog-container.tsx
- components/buylists/search-results/search-results.tsx
- components/main-page-layout.tsx
**Purpose:** The side banners have a padding of 4 so I just added the same padding for the main layout content and the top ad banner so they're not straight up pressed against each other and the header. Also slimmed down the infinite scroll trigger padding in buylists because it was excessive on mobile if you scrolled too fast.
> buylists - updated infinite scroll trigger padding and ad padding

- components/main-page-layout.tsx
- components/ui/navbar.tsx
**Purpose:** Forgot to remove the isAuthenticated check that hides the buylist nav search bar (we now let users query when they're not logged in now). Added bottom padding of 4 to the mainlayout.
> mainlayout bottom padding and fixed hidden buylist navbar bug fix

- pages/buylists/index.tsx
**Purpose:** Disabling buylists until we can get our new chrome extension version published.
> connected vendor bug - disabling buylists
