components/Layout.tsx, components/Navbar.tsx, next.config.js, pages/_app.tsx, pages/advancedsearch.tsx
- For some reason the Link tag in the in the navbar file was set to <a> which caused the reload rerendering issues.
- Also fixed the advanced search and wishlist page from rendering each of the isAuthenticated, and hasSubscription states on reload.
- my prettier formatter made formatting changes that don't actually do anything. the only thing worth noting is bullet point one.
=> navbar fixes

pages/blog/index.tsx, stores/advancedStore.ts
- Update for Stryder: added a toggle for "All Foils" for the advanced search foil dropdown.
=> adding All Foils as a dropdown option in advanced search

components/ad.tsx, components/loading-page.tsx, components/login-required.tsx, components/main-page-layout.tsx, components/single-search/single-results.tsx, components/subscription-required.tsx, pages/_app.tsx, pages/advancedsearch.tsx, pages/blog/[slug].tsx, pages/blog/index.tsx, pages/faq.tsx, pages/forgot-password.tsx, pages/guides/[slug].tsx, pages/guides/index.tsx, pages/index.tsx, pages/multisearch/index.tsx, pages/privacy.tsx, pages/pro.tsx, pages/profile.tsx, pages/reset-password/[token].tsx, pages/signin.tsx, pages/signup.tsx, pages/supporters.tsx, pages/terms.tsx, utils/analytics.ts
- Moved ad layout to `_app.tsx` instead of on each page to avoid re-rendering on navigation to a new page to avoid ad impression inflation
- Memoized in-result ad component to avoid re-rendering of component on browser window resize
=> Ad bugfixes

CHANGELOG.md, pages/forgot-password.tsx, pages/profile.tsx, pages/reset-password/[token].tsx, pages/signin.tsx, pages/signup.tsx, stores/authStore.ts
=> Discord usernames

components/buylists/result-card.tsx, components/ui/select.tsx
**BUYLISTS**
Randomized the selected default store, fixed a css issue with the store dropdown result card, and fixed a bug that made it so all the condition options weren't added.
**BEFORE**
**AFTER**
=> fixed buylist conditions not listing and randomized buylist stores

components/buylists/filter-drop-down-multiple.tsx
Purpose: Forgot to remove a block of buylists UI code I was messing around with from the last PR. It was causing buylist filter mislabling.
=> removing buylist ui code that wasnt supposed to be added

components/buylists/buylist-cart.tsx, components/buylists/buylist-filter-container.tsx, components/buylists/cart-store-accordian.tsx, components/buylists/result-card.tsx, components/homebanner.tsx, components/single-search/single-catalog-container.tsx, components/single-search/single-pagination.tsx, components/theme-toggle.tsx, components/ui/navbar.tsx, pages/buylists/index.tsx, pages/index.tsx, stores/buyListStore.ts, types/product.ts
**Important Note:** Merge the backend PR labeled "SNAP-77 buylist controller pagination & bugfixes" In conjunction with this PR.
**Purpose:** Added Buylist Pagination, Buylist Store Cleanup and interface enforcement, Added Light/Dark Theme Toggle to Nav Bar, UI Adjustments.
**Relevant Files Updated:**
- _components/buylists/buylist-cart.tsx_
- _components/buylists/buylist-filter-container.tsx_
- _components/buylists/cart-store-accordian.tsx_
- _components/buylists/result-card.tsx_
- _components/homebanner.tsx_
- _components/single-search/single-catalog-container.tsx_
- _components/single-search/single-pagination.tsx_
- _components/theme-toggle.tsx_
- _components/ui/navbar.tsx_
- _pages/buylists/index.tsx_
- _pages/index.tsx_
- _stores/buyListStore.ts_
- _types/product.ts_
**Buylist Store …
=> SNAP-77 Buylist pagination

components/search-bar/search-bar.tsx, components/ui/navbar.tsx, pages/buylists/index.tsx, pages/index.tsx
**Purpose:** Remove buylists, fixed filter bug, and added giveaway banner
**Relevant Files Changed:**
_components/search-bar/search-bar.tsx
components/ui/navbar.tsx
pages/buylists/index.tsx
pages/index.tsx_
**Remove Buylists**
Description: Temporarily remove buylists from production to allow us to make adjustments based on our vendor's functional requirements. This will be back soon.
Relevant Files Changed:
- _pages/buylists/index.tsx_
- _components/ui/navbar.tsx_
**Fixed Filter Bug**
**Description:** If the user had filters applied from a previous query on single search and the user typed out a new search query, the previous filters weren't getting cleared and we being forcibly applied.
**Relevant Files Changed:**
- _components/search-bar/search-bar.tsx_
**Added Giveaway Banner** …
=> remove buylists, fixed filter bug, and added giveaway banner

components/ui/navbar.tsx, pages/index.tsx
**Purpose:** Obsidian Games Pokémon Giveaway has ended so I'm removing their home page banner advertising it.
=> remove pokemon giveaway banner

components/single-search/single-catalog-item.tsx
Adding an extra discount for the same store results in an extra object for that same store. I adjusted the logic for showing the store's image link.
=> fixed logo appears more than once in results

components/subscription-options.tsx, pages/profile.tsx
**Purpose:** Remove the text that snapcaster pro members get single search advanced filtering.
=> updated pro info wording

components/ad.tsx, components/main-page-layout.tsx, components/single-search/single-catalog-container.tsx, components/vertical-carousel-ad.tsx, components/vertical-carousel.tsx, stores/globalStore.ts, types/ads.ts, utils/adSelector.ts
- Round robin ads in feed
- Round robin ads in carousels
- Built new vertical carousel component for better ux
=> SNAP-93 Round robin ads

components/main-page-layout.tsx, components/search-bar/nav-search-bar copy.tsx, components/single-search/single-catalog-item.tsx, components/ui/navbar.tsx, components/ui/popover.tsx, stores/globalStore.ts
**Purpose:** Store owner requested a notification banner to let users know that Canada Post is being used again. Added a tool tip to the nav/search bar clarifying how exact search and punctuation works. Fixed a bug that prevented the card finish from being displayed on the single search catalog card such as etched or confetti.
=> Added Search tool Tip, Nav Notification, and Single catalog bugflix

components/search-bar/nav-search-bar copy.tsx, components/single-search/single-catalog-container.tsx, components/single-search/single-filter-container.tsx, components/single-search/single-sort-by.tsx
**Purpose:** Mobile view was missing the sort by drop down for single search so I quickly added it back in.
=> Added sort by in mobile filter box

components/buylists/search.tsx, components/ui/navbar.tsx, stores/buyListStore.ts
**components/ui/navbar.tsx =>** just removing buylist from the navbar ui
**stores/buyListStore.ts =>** adjusted the index for the query params, and set the foiling to any string because there's more variations then the 3 we listed before such as HoloFoil and I dont want to keep maintaining it if new types of these come out.
**Everything else is just formatting from prettier**
=> Buylist UI Patch

components/buylists/buylist-catalog-container.tsx, components/buylists/buylist-catalog-item.tsx, components/buylists/buylist-filter-section.tsx, components/buylists/review.tsx, components/buylists/saved-lists.tsx, components/ui/navbar.tsx, stores/buyListStore.ts
**Buylists:**
- brought back buylists into the nav bar
- added various tooltips
- minor ui adjustments
- prevented increments of any one card past 99 in any given list
=> Brought back buylist in nav plus minor ui updates

components/search-ui/search-bar.tsx, components/ui/select.tsx
The SelectItem component in our shadcn components dont seem to be working on mobile touch screen (from me playing around using prod) even though it works when you enable mobile touch screen mode in your browsers web devtools in local.
I'm hoping this will fix the issue for mobile issues because dropdown selects are not functional it seems.
=> Drop Down Select Item Fix

components/ui/select.tsx
https://github.com/bryceeppler/snapcaster-client/pull/148 did not seem to fix the issue. Trying to fix the mobile touch event not triggering on select by manually setting the click event in the SelectItem Component.
=> Buylist UI

components/sealed/sealed-nav-search-bar.tsx, components/search-ui/nav-search-bar.tsx, components/ui/navbar.tsx, pages/profile.tsx
**Purpose:**
Removed the poorly written state variable usage and replaced the Nav Search Bars Results Toolbar with a factory method that produces them. I left the behavior of the sealed search alone. Fixed a bug introduced last PR which displayed the side banners for pro users.
**Relevant Filed Changed:**
components/sealed/sealed-nav-search-bar.tsx
components/search-ui/nav-search-bar.tsx
components/ui/navbar.tsx
**Removed the poorly written state variable usage in navbar.tsx:**
**Description:** Removed the ternary zustand variables for singles store and buylist store and explicitly declare them depending on the current page path. The Nav Search Bar & Toolbar (The row that contains the # of resutls, pagination, and filter button after you query).
=> nav searchbar adjustment and fixed pro user side banner bug

components/main-page-layout.tsx
**Purpose:** Applying shouldShowAds to the side banners in components/main-page-layout.tsx. Side banners are hidden properly for pro users now.
=> fixed side banners displaying for pro users

components/main-page-layout.tsx
**Purpose:** Minor tweak to the last layout patch I did. I accidently applied it to the vertical padding to the wrong containers
=> added consistent top banner and main layout padding

pages/multisearch/index.tsx
Purpose: Disabled Multisearch until our caching problem is fixed
=> disabled until our multiseach caching is fixed

components/buylists/store-offers/submit-offer-panel.tsx
**Purpose:** Remove a forgotten hard coded p tag in the buylist submission panel component.
=> buylists - fixed hard coded text in buylist submission panel
